import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('./js/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('./styles.css',import.meta.url),'utf8');
assert.match(html,/id="manualAnalysisBtn"/);
assert.match(html,/id="manualAnalysisSidebar"/);
assert.match(html,/id="manualBuildingTabs"/);
assert.match(html,/id="manualSectionTabs"/);
assert.match(html,/id="manualFieldButtons"/);
assert.match(app,/MANUAL_ANALYSIS_SECTIONS/);
assert.match(app,/thermal:\{label:'Thermique'/);
assert.match(app,/carbon:\{label:'Carbone'/);
assert.match(app,/envelope:\{label:'Enveloppe'/);
assert.match(app,/function openManualAnalysisDialog\(/);
assert.match(app,/function manualAnalysisAssignSelection\(/);
assert.match(app,/manualAnalysisAssignSelection\(selectedText\)/);
assert.match(app,/state\.manualValues\[key\]=value/);
assert.match(app,/method:`manual:\$\{loc\?\.selectionMode\|\|'document-analysis'\}`/);
assert.match(css,/manual-field-btn\.active/);
console.log('OK v2.2.6 manual analysis UI and assignment hooks');
